CREATE TABLE IF NOT EXISTS preguntes (
    id INT,
    pregunta TEXT NOT NULL,
    imatge TEXT NOT NULL,
    resposta_correcta INT NOT NULL
);

CREATE TABLE IF NOT EXISTS respostes (
    id INT,
    id_pregunta INT,
    etiqueta TEXT NOT NULL,
    FOREIGN KEY (id_pregunta) REFERENCES preguntes(id)
);

INSERT INTO preguntes (id, pregunta, imatge, resposta_correcta) VALUES
(1, 'Quina és la velocitat màxima permesa en una autopista en condicions normals?', '../web/img/autopista.jpg', 3),
(2, 'Quin document has de portar sempre quan condueixes?', '../web/img/papeles.jpg', 1),
(3, 'Què has de fer quan et trobes amb un semàfor en vermell?', '../web/img/semaforo.jpg', 1),
(4, 'Quina és la norma general per avançar a altres vehicles?', '../web/img/adelantamiento.jpg', 1),
(5, 'Què significa una línia contínua al centre de la carretera?', '../web/img/linea-continua.jpg', 1),
(6, 'Què indica un senyal de stop?', '../web/img/stop.jpg', 1),
(7, 'Quina és la distància mínima que has de mantenir amb el vehicle que vas davant en carreteres secundàries?', '../web/img/distancia.jpg', 3),
(8, 'En quines condicions és obligatori utilitzar el casc?', '../web/img/casco.jpg', 1),
(9, 'Quina és la velocitat màxima en zones urbanes?', '../web/img/urbano.jpg', 2),
(10, 'Què has de fer si arribes a una rotonda amb senyal de cediu el pas?', '../web/img/rotonda.jpg', 1),
(11, 'Què indica una línia d''atenció al conductor a la carretera?', '../web/img/atencion.jpg', 1),
(12, 'Quina norma s''ha de seguir en una intersecció sense senyalització?', '../web/img/interseccio.jpg', 1),
(13, 'Com ha de ser l''ús dels llums en condicions de boira?', '../web/img/boira.jpg', 1),
(14, 'Què indica un senyal triangular amb fons blanc i vora vermella?', '../web/img/ceda.jpg', 1),
(15, 'Quan està permès estacionar davant d''una entrada de garatge?', '../web/img/estacionar.jpg', 1),
(16, 'Què has de fer si et trobes amb una cruïlla sense senyals i un vehicle s''aproxima des de la dreta?', '../web/img/derecha.jpg', 1),
(17, 'Què has de fer quan un vehicle d''emergència amb llums i sirena et supera?', '../web/img/ambulancia.jpg', 1),
(18, 'En quin cas és obligatori utilitzar el cinturó de seguretat?', '../web/img/cinturon.jpg', 1),
(19, 'Quin és l''ús correcte dels llums de carretera en condicions de nit amb visibilitat clara?', '../web/img/carretera_noche.jpg', 1),
(20, 'Com ha de ser la separació entre els vehicles en condicions de pluja intensa?', '../web/img/lluvia.jpg', 1);

INSERT INTO respostes (id_pregunta, etiqueta) VALUES
(1, '80 km/h'),
(1, '100 km/h'),
(1, '120 km/h'),
(1, '140 km/h'),
(2, 'Carnet de conduir'),
(2, 'Passaport'),
(2, 'Document d''identitat'),
(2, 'Assegurança de vida'),
(3, 'Parar'),
(3, 'Continuar amb precaució'),
(3, 'Accelerar'),
(3, 'Reduir la velocitat'),
(4, 'Avançar pel costat esquerre'),
(4, 'Avançar pel costat dret'),
(4, 'Avançar pel mig de la carretera'),
(4, 'No es pot avançar'),
(5, 'No es pot avançar'),
(5, 'Es pot avançar amb precaució'),
(5, 'Línia provisional'),
(5, 'Zona de canvi de carril'),
(6, 'Parar completament i continuar amb precaució'),
(6, 'Reduir la velocitat i continuar'),
(6, 'Passar sense aturar-se'),
(6, 'Canviar de direcció'),
(7, '1 metre'),
(7, '2 metres'),
(7, '4 metres'),
(7, '5 metres'),
(8, 'Quan condueixes una moto o ciclomotor'),
(8, 'Quan condueixes un cotxe'),
(8, 'Quan condueixes una bicicleta només de nit'),
(8, 'Quan condueixes un camió'),
(9, '30 km/h'),
(9, '50 km/h'),
(9, '70 km/h'),
(9, '90 km/h'),
(10, 'Cedir el pas als vehicles que circulen per la rotonda'),
(10, 'Entrar sense aturar-se'),
(10, 'Aturar-se completament abans de continuar'),
(10, 'Canviar de direcció sense mirar'),
(11, 'Que estàs a punt de sortir de la carretera'),
(11, 'Que és zona d''estacionament'),
(11, 'Que has de reduir la velocitat'),
(11, 'Que la carretera és perillosa'),
(12, 'Respectar la prioritat de la dreta'),
(12, 'Sempre tenir prioritat'),
(12, 'Prioritzar el trànsit del carrer principal'),
(12, 'Aturar-se i comprovar els altres vehicles'),
(13, 'Utilitzar llums de boira'),
(13, 'Utilitzar llums d''ús diürn'),
(13, 'Utilitzar només els llums de posició'),
(13, 'No utilitzar cap llum'),
(14, 'Advertència de perill'),
(14, 'Obligació de detenció'),
(14, 'Restricció de velocitat'),
(14, 'Prohibició d''entrada'),
(15, 'Mai'),
(15, 'Només si hi ha senyalització que ho permet'),
(15, 'Quan el garatge no està en ús'),
(15, 'Durant la nit'),
(16, 'Cedir el pas'),
(16, 'Continuar sense parar'),
(16, 'Accelerar per passar primer'),
(16, 'Aturar-te i esperar'),
(17, 'Mantenir-te a la dreta i reduir la velocitat'),
(17, 'Accelerar per no bloquejar el pas'),
(17, 'Aturar-te al mig de la carretera'),
(17, 'Seguir el vehicle d''emergència'),
(18, 'Sempre, tant si vas com a conductor com a passatger'),
(18, 'Només quan condueixes per autopistes'),
(18, 'Només si viatges a la part del davant del vehicle'),
(18, 'Només per a passatgers majors de 12 anys'),
(19, 'Utilitzar els llums d''altes'),
(19, 'Utilitzar els llums de creuer'),
(19, 'Utilitzar els llums de posició'),
(19, 'Apagar els llums'),
(20, 'Més gran de l''habitual'),
(20, 'Menys gran de l''habitual'),
(20, 'Igual que en condicions normals'),
(20, 'No cal preocupar-se per la separació');